package com.test;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class ReplaceWords {

   public static void main(String[] args)  {
	
	   long start = System.currentTimeMillis();
	   
	   Map<String,String> variableMap= fillMap();
	   Path path = Paths.get("C:\\Users\\SRINATH\\Desktop\\t8.shakespeare.txt");
	   Path path1 = Paths.get("C:\\Users\\SRINATH\\Desktop\\t8.shakespeare.translated.txt");
	   Stream<String> lines;
	try {
		lines = Files.lines(path,Charset.forName("UTF-8"));

		   List<String> replacedLines = lines.map(line -> replaceTag(line,variableMap))
				   													.collect(Collectors.toList());
		   Files.write(path1, replacedLines, Charset.forName("UTF-8"));
		   lines.close();
		   System.out.println("Find and replace done..");
	} catch (IOException e) {
	
		e.printStackTrace();
	}	  
	
	 long end = System.currentTimeMillis();
	   System.out.println("Time taken to process: "+ (end-start) +" milliseconds");
   }
   public static Map<String,String> fillMap(){
	   
	   Map<String,String> map = new HashMap<String,String>();
	   map.put("abide", "respecter");
	   map.put("about", "sur");
	   map.put("above", "au dessus");
	   map.put("abroad", "à l'étranger");
	   map.put("abuse", "abuser de");
	   map.put("according", "selon");
	   map.put("account", "Compte");
	   map.put("accuse", "accuser");
	   map.put("acquainted", "connaissance");
	   map.put("action", "action");
	   map.put("advantage", "advantage");
	   map.put("advice", "Conseil");
	   map.put("affairs", "affaires");
	   map.put("affection", "affection");
	   map.put("affections", "affections");
	   map.put("afraid", "peur");
	   map.put("after", "après");
	   map.put("afterwards", "ensuite");
	   map.put("again", "encore");
	   map.put("alive", "vivant");
	   map.put("almost", "presque");
	   map.put("alone", "seul");
	   map.put("along", "le long de");
	   map.put("already", "déjà");
	   map.put("although", "bien que");
	   map.put("always", "toujours");
	   map.put("ambition", "ambition");
	   map.put("ancient", "ancien");
	   map.put("angel", "ange");
	   map.put("anger", "colère");
	   map.put("another", "un autre");
	   map.put("answer", "répondre");
	   map.put("anything", "n'importe quoi");
	   map.put("apparel", "vêtements");
	   map.put("appear", "apparaître");
	   map.put("appears", "apparaît");
	   map.put("approach", "approche");
	   map.put("argument", "argument");
	   map.put("ariel", "Ariel");
	   map.put("armour", "armure");
	   map.put("aside", "de côté");
	   map.put("asleep", "endormi");
	   map.put("assure", "assurer");
	   map.put("athens", "absence");
	   map.put("attend", "assister");
	   map.put("attended", "assisté");
	   map.put("authority", "autorité");
	   map.put("avoid", "éviter");
	   map.put("awake", "éveillé");
	   map.put("awhile", "quelque temps");
	   map.put("banish", "bannir");
	   map.put("barren", "Dénudé");
	   map.put("banish", "bannir");
	   map.put("barren", "Dénudé");
	   map.put("bassianus", "bassianus");
	   map.put("bastard", "Connard");
	   map.put("battle", "bataille");
	   map.put("beard", "barbe");
	   map.put("bearing", "palier");
	   map.put("bears", "ours");
	   map.put("beast", "la bête");
	   map.put("beaten", "battu");
	   map.put("beauty", "beauté");
	   map.put("because", "car");
	   map.put("become", "devenir");
	   map.put("bedford", "Bedford");
	   map.put("before", "avant");
	   map.put("beggar", "mendiant");
	   map.put("begin", "commencer");
	   map.put("behalf", "nom");
	   map.put("behind", "derrière");
	   map.put("behold", "voir");
	   map.put("being", "étant");
	   map.put("believe", "croyez");
	   map.put("belike", "être comme");
	   map.put("below", "au dessous de");
	   map.put("benefit", "avantage");
	   map.put("besides", "outre");
	   map.put("betray", "trahir");
	   map.put("better", "mieux");
	   map.put("between", "entre");
	   map.put("beyond", "au-delà");
	   map.put("birth", "naissance");
	   map.put("bishop", "évêque");
	   map.put("bitter", "amer");
	   map.put("black", "noir");
	   map.put("blame", "faire des reproches");
	   map.put("bless", "bénir");
	   map.put("blessing", "bénédiction");
	   map.put("blest", "heureux");
	   map.put("blind", "aveugle");
	   map.put("blood", "du sang");
	   map.put("blows", "coups");
	   map.put("blunt", "cru");
	   map.put("blush", "rougir");
	   map.put("bodies", "corps");
	   map.put("bones", "des os");
	   map.put("borne", "supporté");
	   map.put("bottom", "bas");
	   map.put("bought", "acheté");
	   map.put("bound", "lié");
	   map.put("bounty", "prime");
	   map.put("brain", "cerveau");
	   map.put("brains", "cerveaux");
	   map.put("brave", "courageux");
	   map.put("breast", "Sein");
	   map.put("breath", "souffle");
	   map.put("breed", "race");
	   map.put("brief", "bref");
	   map.put("bright", "brillant");
	   map.put("bring", "apporter");
	   map.put("broke", "cassé");
	   map.put("brook", "ruisseau");
	   map.put("brother", "frère");
	   map.put("brought", "apporté");
	   map.put("brows", "sourcils");
	   map.put("burden", "fardeau");
	   map.put("buried", "enterré");
	   map.put("burning", "brûlant");
	   map.put("business", "Entreprise");
	   map.put("cannot", "ne peux pas");
	   map.put("capitol", "Capitole");
	   map.put("captain", "capitaine");
	   map.put("cardinal", "cardinal");
	   map.put("cares", "se soucie");
	   map.put("carry", "porter");
	   map.put("castle", "Château");
	   map.put("catch", "capture");
	   map.put("cause", "cause");
	   map.put("cease", "cesser");
	   map.put("certain", "certain");
	   map.put("chain", "chaîne");
	   map.put("chair", "chaise");
	   map.put("challenge", "défi");
	   map.put("chamber", "chambre");
	   map.put("chance", "chance");
	   map.put("change", "changement");
	   map.put("charge", "charge");
	   map.put("charity", "charité");
	   map.put("chaste", "chaste");
	   map.put("cheek", "joue");
	   map.put("cheer", "acclamation");
	   map.put("chide", "chide");
	   map.put("chief", "chef");
	   map.put("child", "enfant");
	   map.put("choice", "choix");
	   map.put("church", "église");
	   map.put("cinna", "cinna");
	   map.put("citizen", "citoyenne");
	   map.put("civil", "civil");
	   map.put("claim", "prétendre");
	   map.put("clarence", "clarté");
	   map.put("claud", "claud");
	   map.put("claudio", "claudio");
	   map.put("clear", "clair");
	   map.put("clifford", "clifford");
	   map.put("close", "proche");
	   map.put("cloten", "cailloter");
	   map.put("clothes", "vêtements");
	   map.put("clouds", "des nuages");
	   map.put("clown", "pitre");
	   map.put("college", "Université");
	   map.put("colour", "Couleur");
	   map.put("comes", "vient");
	   map.put("comfort", "confort");
	   map.put("coming", "venir");
	   map.put("cominius", "cominius");
	   map.put("command", "commander");
	   map.put("commanded", "commandé");
	   map.put("commend", "saluer");
	   map.put("commercial", "commercial");
	   map.put("commission", "commission");
	   map.put("commit", "commettre");
	   map.put("common", "commun");
	   map.put("companion", "un compagnon");
	   map.put("company", "entreprise");
	   map.put("complete", "Achevée");
	   map.put("complexion", "complexion");
	   map.put("condition", "état");
	   map.put("conduct", "conduite");
	   map.put("confess", "avouer");
	   map.put("conscience", "conscience");
	   map.put("consent", "consentement");
	   map.put("consider", "considérer");
	   map.put("constable", "gendarme");
	   map.put("constant", "constant");
	   map.put("contempt", "mépris");
	   map.put("content", "contenu");
	   map.put("contrary", "contraire");
	   map.put("copies", "copies");
	   map.put("copyright", "droits d'auteur");
	   map.put("could", "pourrait");
	   map.put("council", "conseil");
	   map.put("counsel", "Conseil");
	   map.put("count", "compter");
	   map.put("counterfeit", "contrefaire");
	   map.put("countess", "comtesse");
	   map.put("country", "pays");
	   map.put("courage", "courage");
	   map.put("course", "cours");
	   map.put("court", "tribunal");
	   map.put("courtesy", "courtoisie");
	   map.put("cousin", "cousin");
	   map.put("coward", "lâche");
	   map.put("crave", "demander");
	   map.put("creature", "créature");
	   map.put("credit", "crédit");
	   map.put("cromwell", "Cromwell");
	   map.put("cross", "traverser");
	   map.put("crown", "couronne");
	   map.put("cruel", "cruel");
	   map.put("cunning", "ruse");
	   map.put("cupid", "Cupidon");
	   map.put("curse", "malédiction");
	   map.put("custom", "Douane");
	   map.put("dagger", "dague");
	   map.put("damned", "damné");
	   map.put("dance", "Danse");
	   map.put("danger", "danger");
	   map.put("darkness", "obscurité");
	   map.put("daughter", "fille");
	   map.put("deadly", "mortel");
	   map.put("dearest", "très cher");
	   map.put("dearly", "chèrement");
	   map.put("death", "décès");
	   map.put("deeds", "actes");
	   map.put("defend", "défendre");
	   map.put("degree", "diplôme");
	   map.put("delight", "délice");
	   map.put("deliver", "livrer");
	   map.put("demand", "demande");
	   map.put("denied", "refusé");
	   map.put("depart", "depart");
	   map.put("desert", "désert");
	   map.put("deserve", "mériter");
	   map.put("desire", "le désir");
	   map.put("despair", "désespoir");
	   map.put("desperate", "désespéré");
	   map.put("despite", "malgré");
	   map.put("device", "dispositif");
	   map.put("devil", "diable");
	   map.put("devise", "concevoir");
	   map.put("didst", "didst");
	   map.put("dinner", "dîner");
	   map.put("discourse", "discours");
	   map.put("discover", "découvrir");
	   map.put("disgrace", "disgrâce");
	   map.put("dishonour", "déshonorer");
	   map.put("dispatch", "envoi");
	   map.put("displeasure", "mécontentement");
	   map.put("disposition", "disposition");
	   map.put("distributed", "distribué");
	   map.put("divine", "Divin");
	   map.put("doctor", "docteur");
	   map.put("doing", "Faire");
	   map.put("dolabella", "Dolabella");
	   map.put("doors", "des portes");
	   map.put("double", "double");
	   map.put("doubt", "doute");
	   map.put("download", "Télécharger");
	   map.put("dramatis", "dramatis");
	   map.put("drawn", "tiré");
	   map.put("dread", "crainte");
	   map.put("dreadful", "dreadful");
	   map.put("dream", "rêver");
	   map.put("dreams", "rêves");
	   map.put("drink", "boisson");
	   map.put("drops", "gouttes");
	   map.put("drown", "noyer");
	   map.put("drums", "tambours");
	   map.put("drunk", "ivre");
	   map.put("duncan", "Duncan");
	   map.put("durst", "durst");
	   map.put("dwell", "habiter");
	   map.put("dying", "en train de mourir");
	   map.put("early", "de bonne heure");
	   map.put("earth", "Terre");
	   map.put("edmund", "Edmund");
	   map.put("effect", "effet");
	   map.put("egypt", "Egypte");
	   map.put("either", "Soit");
	   map.put("elbow", "coude");
	   map.put("elder", "aîné");
	   map.put("embrace", "embrasse");
	   map.put("emilia", "Émilie");
	   map.put("emperor", "empereur");
	   map.put("empty", "vide");
	   map.put("encounter", "encounter");
	   map.put("endure", "supporter");
	   map.put("enemies", "ennemis");
	   map.put("enemy", "ennemi");
	   map.put("enjoy", "prendre plaisir");
	   map.put("enobarbus", "énobarbus");
	   map.put("enough", "assez");
	   map.put("enter", "entrer");
	   map.put("entertain", "divertir");
	   map.put("entertainment", "entertainment");
	   map.put("entreat", "supplier");
	   map.put("equal", "égal");
	   map.put("estate", "biens");
	   map.put("eternal", "éternel");
	   map.put("every", "chaque");
	   map.put("everything", "tout");
	   map.put("excellent", "excellent");
	   map.put("except", "sauf");
	   map.put("excuse", "excuse");
	   map.put("execution", "exécution");
	   map.put("exeter", "Exeter");
	   map.put("exeunt", "sortir");
	   map.put("express", "Express");
	   map.put("faces", "visages");
	   map.put("faint", "perdre connaissance");
	   map.put("fairy", "Fée");
	   map.put("faith", "Foi");
	   map.put("falls", "des chutes");
	   map.put("FALSE", "faux");
	   map.put("familiar", "familier");
	   map.put("fancy", "fantaisie");
	   map.put("farewell", "adieu");
	   map.put("farther", "plus loin");
	   map.put("fashion", "mode");
	   map.put("fatal", "fatal");
	   map.put("father", "père");
	   map.put("fault", "faute");
	   map.put("favour", "favoriser");
	   map.put("fearful", "craintif");
	   map.put("fears", "peurs");
	   map.put("feast", "le banquet");
	   map.put("feeble", "faible");
	   map.put("fellow", "compagnon");
	   map.put("fenton", "Fenton");
	   map.put("ferdinand", "Ferdinand");
	   map.put("fetch", "chercher");
	   map.put("field", "champ");
	   map.put("fiend", "démon");
	   map.put("fierce", "féroce");
	   map.put("fiery", "ardent");
	   map.put("fight", "bats toi");
	   map.put("figure", "figure");
	   map.put("finds", "trouve");
	   map.put("finger", "doigt");
	   map.put("first", "première");
	   map.put("flatter", "flatter");
	   map.put("flesh", "la chair");
	   map.put("flies", "mouches");
	   map.put("flight", "vol");
	   map.put("flood", "inonder");
	   map.put("flourish", "fleurir");
	   map.put("flower", "fleur");
	   map.put("flowers", "fleurs");
	   map.put("follow", "suivre");
	   map.put("folly", "folie");
	   map.put("foolish", "insensé");
	   map.put("fools", "imbéciles");
	   map.put("forbear", "ancêtre");
	   map.put("forbid", "interdire");
	   map.put("force", "Obliger");
	   map.put("forces", "les forces");
	   map.put("forest", "forêt");
	   map.put("forget", "oublier");
	   map.put("former", "ancien");
	   map.put("forsooth", "en vérité");
	   map.put("forth", "en avant");
	   map.put("fortune", "fortune");
	   map.put("forward", "vers l'avant");
	   map.put("fought", "combattu");
	   map.put("found", "a trouvé");
	   map.put("fourth", "Quatrième");
	   map.put("frame", "Cadre");
	   map.put("france", "France");
	   map.put("freely", "librement");
	   map.put("french", "français");
	   map.put("fresh", "Frais");
	   map.put("friend", "ami");
	   map.put("frown", "froncer les sourcils");
	   map.put("fruit", "fruit");
	   map.put("further", "plus loin");
	   map.put("gallant", "galant");
	   map.put("garden", "jardin");
	   map.put("gates", "portes");
	   map.put("gaunt", "décharné");
	   map.put("general", "général");
	   map.put("gentle", "doux");
	   map.put("ghost", "fantôme");
	   map.put("given", "donné");
	   map.put("giving", "donnant");
	   map.put("glass", "verre");
	   map.put("glorious", "glorieux");
	   map.put("glory", "gloire");
	   map.put("going", "Aller");
	   map.put("golden", "d'or");
	   map.put("goodness", "la bonté");
	   map.put("gower", "gower");
	   map.put("grace", "la grâce");
	   map.put("grant", "subvention");
	   map.put("grave", "la tombe");
	   map.put("great", "génial");
	   map.put("green", "vert");
	   map.put("greet", "saluer");
	   map.put("grief", "douleur");
	   map.put("grieve", "pleurer");
	   map.put("gross", "brut");
	   map.put("ground", "sol");
	   map.put("grown", "grandi");
	   map.put("guard", "garde");
	   map.put("guard", "garde");
	   map.put("guess", "devine");
	   map.put("guilty", "coupable");
	   map.put("habit", "habitude");
	   map.put("hands", "mains");
	   map.put("hanging", "pendaison");
	   map.put("hangs", "bloque");
	   map.put("happiness", "bonheur");
	   map.put("happy", "heureux");
	   map.put("haste", "hâte");
	   map.put("hateful", "odieux");
	   map.put("having", "ayant");
	   map.put("hazard", "danger");
	   map.put("heads", "têtes");
	   map.put("health", "santé");
	   map.put("heard", "entendu");
	   map.put("heart", "cœur");
	   map.put("heaven", "paradis");
	   map.put("heavy", "lourd");
	   map.put("hector", "Hector");
	   map.put("heels", "talons");
	   map.put("hence", "Par conséquent");
	   map.put("henceforth", "désormais");
	   map.put("hereafter", "ci-après, par la suite");
	   map.put("herself", "se");
	   map.put("highness", "altesse");
	   map.put("holds", "tient");
	   map.put("hollow", "creux");
	   map.put("honest", "honnête");
	   map.put("horse", "cheval");
	   map.put("hostess", "hôtesse");
	   map.put("hours", "heures");
	   map.put("house", "maison");
	   map.put("hubert", "Hubert");
	   map.put("humble", "humble");
	   map.put("humour", "humour");
	   map.put("hundred", "cent");
	   map.put("guard", "garde");
	   map.put("husband", "mari");
	   map.put("ignorant", "ignorant");
	   map.put("image", "image");
	   map.put("includes", "comprend");
	   map.put("indeed", "En effet");
	   map.put("infinite", "infini");
	   map.put("innocent", "innocent");
	   map.put("instant", "instant");
	   map.put("intend", "avoir l'intention");
	   map.put("intent", "intention");
	   map.put("issue", "problème");
	   map.put("itself", "lui-même");
	   map.put("jealous", "jaloux");
	   map.put("jewel", "bijou");
	   map.put("judge", "juge");
	   map.put("judgment", "jugement");
	   map.put("julia", "Julia");
	   map.put("justice", "Justice");
	   map.put("keeps", "garde");
	   map.put("kindness", "la gentillesse");
	   map.put("kingdom", "Royaume");
	   map.put("kings", "rois");
	   map.put("knave", "fripon");
	   map.put("kneel", "s'agenouiller");
	   map.put("knees", "les genoux");
	   map.put("knife", "couteau");
	   map.put("knight", "Chevalier");
	   map.put("knock", "frappe");
	   map.put("knowing", "connaissance");
	   map.put("knowledge", "connaissance");
	   map.put("known", "connu");
	   map.put("knows", "sait");
	   map.put("labour", "la main d'oeuvre");
	   map.put("ladies", "Dames");
	   map.put("ladyship", "Madame");
	   map.put("lands", "terres");
	   map.put("large", "grand");
	   map.put("laugh", "rire");
	   map.put("launce", "lancer");
	   map.put("lawful", "légitime");
	   map.put("learn", "apprendre");
	   map.put("learned", "appris");
	   map.put("least", "moins");
	   map.put("leave", "laisser");
	   map.put("leisure", "loisir");
	   map.put("leontes", "leontes");
	   map.put("letter", "lettre");
	   map.put("liberty", "liberté");
	   map.put("library", "bibliothèque");
	   map.put("liege", "Liege");
	   map.put("lieutenant", "lieutenant");
	   map.put("light", "lumière");
	   map.put("limbs", "membres");
	   map.put("little", "peu");
	   map.put("lives", "vies");
	   map.put("living", "vivant");
	   map.put("longer", "plus long");
	   map.put("looks", "regards");
	   map.put("loose", "ample");
	   map.put("lords", "seigneurs");
	   map.put("lordship", "seigneurie");
	   map.put("lorenzo", "Lorenzo");
	   map.put("lovely", "charmant");
	   map.put("lovers", "les amoureux");
	   map.put("loves", "aime");
	   map.put("loving", "aimant");
	   map.put("lucentio", "Lucentio");
	   map.put("machine", "machine");
	   map.put("madness", "la démence");
	   map.put("maiden", "jeune fille");
	   map.put("maids", "servantes");
	   map.put("maintain", "macintenir");
	   map.put("majesty", "majesté");
	   map.put("makes", "fait du");
	   map.put("making", "fabrication");
	   map.put("malice", "malice");
	   map.put("manner", "manière");
	   map.put("march", "Mars");
	   map.put("marcius", "Marcius");
	   map.put("marcus", "Marcus");
	   map.put("margaret", "margaret");
	   map.put("maria", "maria");
	   map.put("mariana", "Mariana");
	   map.put("marriage", "mariage");
	   map.put("marry", "marier");
	   map.put("master", "Maître");
	   map.put("match", "rencontre");
	   map.put("matter", "matière");
	   map.put("meaning", "sens");
	   map.put("means", "veux dire");
	   map.put("meant", "signifiait");
	   map.put("measure", "mesure");
	   map.put("meeting", "réunion");
	   map.put("membership", "adhésion");
	   map.put("memory", "Mémoire");
	   map.put("merchant", "marchande");
	   map.put("mercy", "pitié");
	   map.put("merit", "mérite");
	   map.put("merry", "joyeux");
	   map.put("messenger", "Messager");
	   map.put("midnight", "minuit");
	   map.put("might", "pourrait");
	   map.put("mighty", "puissant");
	   map.put("milan", "Milan");
	   map.put("minds", "esprits");
	   map.put("minister", "ministre");
	   map.put("miranda", "Miranda");
	   map.put("mirth", "gaieté");
	   map.put("mischief", "sottises");
	   map.put("misery", "misère");
	   map.put("mistake", "erreur");
	   map.put("mistress", "maîtresse");
	   map.put("modest", "modeste");
	   map.put("money", "argent");
	   map.put("monster", "monstre");
	   map.put("month", "mois");
	   map.put("morning", "Matin");
	   map.put("morrow", "demain");
	   map.put("mortal", "mortel");
	   map.put("mother", "mère"); 
	   map.put("motion", "mouvement");
	   map.put("mouth", "bouche");
	   map.put("mowbray", "mowbray");
	   map.put("murder", "meurtre");
	   map.put("murther", "aller plus loin");
	   map.put("music", "la musique");
	   map.put("myself", "moi même");
	   map.put("naked", "nu");
	   map.put("names", "des noms");
	   map.put("native", "originaire de");
	   map.put("natural", "Naturel");
	   map.put("nature", "la nature");
	   map.put("needs", "Besoins");
	   map.put("neighbour", "voisine");
	   map.put("neither", "ni");
	   map.put("never", "jamais");
	   map.put("niece", "nièce");
	   map.put("night", "nuit");
	   map.put("noble", "noble");
	   map.put("noise", "bruit");
	   map.put("nothing", "rien");
	   map.put("nought", "néant");
	   map.put("number", "nombre");
	   map.put("nurse", "infirmière");
	   map.put("oaths", "serments");
	   map.put("obedience", "obéissance");
	   map.put("oberon", "Oberon");
	   map.put("object", "objet");
	   map.put("occasion", "occasion");
	   map.put("offence", "infraction");
	   map.put("offend", "offenser");
	   map.put("offer", "offre");
	   map.put("office", "Bureau");
	   map.put("often", "souvent");
	   map.put("oliver", "oliver");
	   map.put("opinion", "opinion");
	   map.put("order", "ordre");
	   map.put("orlando", "orlando");
	   map.put("other", "autre");
	   map.put("others", "autres");
	   map.put("ourselves", "nous-mêmes");
	   map.put("outward", "vers l'extérieur");
	   map.put("oxford", "Oxford");
	   map.put("padua", "Padoue");
	   map.put("pains", "des douleurs");
	   map.put("painted", "peint");
	   map.put("painter", "peintre");
	   map.put("palace", "palais");
	   map.put("pandarus", "pandarus");
	   map.put("paper", "papier");
	   map.put("pardon", "pardon");
	   map.put("paris", "Paris");
	   map.put("parolles", "parolles");
	   map.put("parted", "séparé");
	   map.put("particular", "particulier");
	   map.put("partly", "partiellement");
	   map.put("parts", "les pièces");
	   map.put("party", "fête");
	   map.put("passage", "passage");
	   map.put("passion", "la passion");
	   map.put("patience", "la patience");
	   map.put("patient", "patient");
	   map.put("paulina", "paulina");
	   map.put("peace", "paix");
	   map.put("pedro", "pedro");
	   map.put("people", "gens");
	   map.put("perceive", "apercevoir");
	   map.put("percy", "Percy");
	   map.put("perfect", "parfait");
	   map.put("perhaps", "peut-être");
	   map.put("peril", "péril");
	   map.put("permission", "autorisation");
	   map.put("person", "la personne");
	   map.put("personal", "personnel");
	   map.put("phebe", "phebe");
	   map.put("philip", "Philippe");
	   map.put("picture", "image");
	   map.put("piece", "pièce");
	   map.put("pistol", "pistolet");
	   map.put("place", "endroit");
	   map.put("plague", "peste");
	   map.put("plain", "plaine");
	   map.put("plead", "plaider");
	   map.put("please", "S'il vous plaît");
	   map.put("pleasure", "plaisir");
	   map.put("pluck", "cueillir");
	   map.put("poins", "poins");
	   map.put("point", "point");
	   map.put("poison", "poison");
	   map.put("policy", "politique");
	   map.put("polixenes", "polixènes");
	   map.put("pompey", "pompey");
	   map.put("porter", "porter");
	   map.put("possible", "possible");
	   map.put("posthumus", "posthume");
	   map.put("pound", "livre");
	   map.put("power", "Puissance");
	   map.put("practice", "entraine toi");
	   map.put("praise", "louange");
	   map.put("prayers", "prières");
	   map.put("precious", "précieux");
	   map.put("prepare", "préparer");
	   map.put("presence", "présence");
	   map.put("present", "présent");
	   map.put("pretty", "jolie");
	   map.put("pride", "fierté");
	   map.put("priest", "prêtre");
	   map.put("prince", "prince");
	   map.put("prison", "prison");
	   map.put("private", "privé");
	   map.put("prize", "prix");
	   map.put("proceed", "procéder");
	   map.put("proclaim", "proclamer");
	   map.put("profit", "profit");
	   map.put("prohibited", "interdit");
	   map.put("project", "projet");
	   map.put("prologue", "prologue");
	   map.put("promise", "promettre");
	   map.put("proof", "preuve");
	   map.put("proper", "correct");
	   map.put("protector", "protecteur");
	   map.put("protest", "manifestation");
	   map.put("proud", "fier");
	   map.put("prove", "prouver");
	   map.put("provided", "à condition de");
	   map.put("public", "Publique");
	   map.put("purpose", "objectif");
	   map.put("purse", "bourse");
	   map.put("quality", "qualité");
	   map.put("quarrel", "querelle");
	   map.put("queen", "reine");
	   map.put("question", "question");
	   map.put("quick", "rapide");
	   map.put("quiet", "silencieux");
	   map.put("quite", "assez");
	   map.put("quoth", "quoth");
	   map.put("raise", "élever");
	   map.put("ransom", "une rançon");
	   map.put("rascal", "coquin");
	   map.put("rather", "plutôt");
	   map.put("readable", "lisible");
	   map.put("ready", "prêt");
	   map.put("realm", "domaine");
	   map.put("reason", "raison");
	   map.put("receive", "recevoir");
	   map.put("regard", "qui concerne");
	   map.put("reign", "règne");
	   map.put("reignier", "règne");
	   map.put("remain", "rester");
	   map.put("remedy", "remède");
	   map.put("remember", "rappelles toi");
	   map.put("render", "rendre");
	   map.put("repair", "réparation");
	   map.put("repent", "se repentir");
	   map.put("report", "rapport");
	   map.put("reputation", "réputation");
	   map.put("request", "demande");
	   map.put("respect", "le respect");
	   map.put("return", "revenir");
	   map.put("revenge", "vengeance");
	   map.put("reverence", "révérence");
	   map.put("revolt", "révolte");
	   map.put("right", "droite");
	   map.put("rivers", "rivières");
	   map.put("rogue", "coquin");
	   map.put("rotten", "pourri");
	   map.put("rough", "rugueux");
	   map.put("round", "rond");
	   map.put("royal", "Royal");
	   map.put("sacred", "sacré");
	   map.put("safety", "sécurité");
	   map.put("saint", "Saint");
	   map.put("salerio", "salerio");
	   map.put("satisfied", "satisfait");
	   map.put("saying", "en disant");
	   map.put("scarce", "rare");
	   map.put("scene", "scène");
	   map.put("scorn", "mépris");
	   map.put("search", "chercher");
	   map.put("season", "saison");
	   map.put("second", "seconde");
	   map.put("secret", "secret");
	   map.put("seeing", "voyant");
	   map.put("senate", "sénat");
	   map.put("senator", "sénateur");
	   map.put("sense", "sens");
	   map.put("sentence", "phrase");
	   map.put("servant", "serviteur");
	   map.put("serve", "servir");
	   map.put("service", "un service");
	   map.put("seven", "Sept");
	   map.put("several", "nombreuses");
	   map.put("shadow", "ombre");
	   map.put("shake", "secouer");
	   map.put("shall", "doit");
	   map.put("shame", "la honte");
	   map.put("shape", "forme");
	   map.put("sharp", "tranchant");
	   map.put("shepherd", "berger");
	   map.put("shine", "éclat");
	   map.put("shore", "rive");
	   map.put("short", "court");
	   map.put("shortly", "prochainement");
	   map.put("should", "devrait");
	   map.put("shows", "montre");
	   map.put("sickness", "maladie");
	   map.put("sight", "vue");
	   map.put("silence", "silence");
	   map.put("silver", "argent");
	   map.put("simple", "Facile");
	   map.put("since", "depuis");
	   map.put("single", "Célibataire");
	   map.put("sirrah", "sirrah");
	   map.put("sister", "sœur");
	   map.put("skill", "compétence");
	   map.put("slain", "tué");
	   map.put("slander", "calomnie");
	   map.put("slave", "esclave");
	   map.put("sleep", "sommeil");
	   map.put("slender", "mince");
	   map.put("small", "petit");
	   map.put("smell", "odeur");
	   map.put("smile", "sourire");
	   map.put("soldier", "soldat");
	   map.put("solemn", "solennel");
	   map.put("somerset", "somerset");
	   map.put("something", "quelque chose");
	   map.put("sometime", "parfois");
	   map.put("sooner", "plus tôt");
	   map.put("soothsayer", "devin");
	   map.put("sorrow", "chagrin");
	   map.put("sorry", "Pardon");
	   map.put("sought", "recherché");
	   map.put("souls", "âmes");
	   map.put("sound", "du son");
	   map.put("sovereign", "souverain");
	   map.put("spare", "de rechange");
	   map.put("speak", "parler");
	   map.put("speaks", "parle");
	   map.put("special", "spécial");
	   map.put("speech", "discours");
	   map.put("speed", "la vitesse");
	   map.put("spend", "dépenser");
	   map.put("spirit", "esprit");
	   map.put("spite", "dépit");
	   map.put("spoke", "parlait");
	   map.put("sport", "sport");
	   map.put("spring", "printemps");
	   map.put("staff", "Personnel");
	   map.put("stain", "tache");
	   map.put("stand", "supporter");
	   map.put("stars", "étoiles");
	   map.put("state", "Etat");
	   map.put("steal", "voler");
	   map.put("steel", "acier");
	   map.put("steward", "intendant");
	   map.put("still", "encore");
	   map.put("stomach", "estomac");
	   map.put("stone", "calcul");
	   map.put("stood", "se tenait");
	   map.put("store", "boutique");
	   map.put("storm", "orage");
	   map.put("story", "récit");
	   map.put("straight", "tout droit");
	   map.put("strange", "étrange");
	   map.put("street", "rue");
	   map.put("strength", "force");
	   map.put("strike", "la grève");
	   map.put("stroke", "accident vasculaire cérébral");
	   map.put("strong", "fort");
	   map.put("struck", "frappé");
	   map.put("study", "étude");
	   map.put("stuff", "des trucs");
	   map.put("subject", "matière");
	   map.put("substance", "substance");
	   map.put("success", "Succès");
	   map.put("sudden", "soudain");
	   map.put("suddenly", "tout à coup");
	   map.put("suffer", "souffrir");
	   map.put("suffolk", "suffolk");
	   map.put("summer", "été");
	   map.put("supper", "souper");
	   map.put("surely", "sûrement");
	   map.put("surrey", "Surrey");
	   map.put("suspect", "suspect");
	   map.put("swear", "jurer");
	   map.put("sweat", "transpiration");
	   map.put("sweet", "sucré");
	   map.put("swift", "rapide");
	   map.put("sword", "épée");
	   map.put("swore", "juré");
	   map.put("sworn", "juré");
	   map.put("syracuse", "Syracuse");
	   map.put("table", "table");
	   map.put("tailor", "tailleur");
	   map.put("taken", "pris");
	   map.put("talbot", "talbot");
	   map.put("tarry", "goudronneux");
	   map.put("taste", "goût");
	   map.put("taught", "enseigné");
	   map.put("teach", "enseigner");
	   map.put("tears", "larmes");
	   map.put("tedious", "fastidieux");
	   map.put("teeth", "les dents");
	   map.put("tells", "raconte");
	   map.put("tempest", "tempête");
	   map.put("tender", "soumissionner");
	   map.put("terms", "termes");
	   map.put("thank", "remercier");
	   map.put("their", "leur");
	   map.put("themselves", "se");
	   map.put("there", "Là");
	   map.put("therefore", "par conséquent");
	   map.put("therein", "la bride");
	   map.put("these", "celles-ci");
	   map.put("thief", "voleur");
	   map.put("thing", "chose");
	   map.put("think", "pense");
	   map.put("third", "troisième");
	   map.put("thomas", "Thomas");
	   map.put("those", "ceux");
	   map.put("though", "bien que");
	   map.put("thought", "pensée");
	   map.put("thrive", "prospérer");
	   map.put("throat", "gorge");
	   map.put("throne", "trône");
	   map.put("through", "par");
	   map.put("throw", "jeter");
	   map.put("thrust", "poussée");
	   map.put("thunder", "tonnerre");
	   map.put("times", "fois");
	   map.put("title", "Titre");
	   map.put("together", "ensemble");
	   map.put("tongue", "langue");
	   map.put("tonight", "ce soir");
	   map.put("touch", "toucher");
	   map.put("toward", "vers");
	   map.put("tower", "la tour");
	   map.put("train", "train");
	   map.put("traitor", "traitre");
	   map.put("tread", "bande de roulement");
	   map.put("treason", "trahison");
	   map.put("treasure", "Trésor");
	   map.put("trial", "procès");
	   map.put("tribunes", "tribunes");
	   map.put("trick", "tour");
	   map.put("triumph", "triomphe");
	   map.put("trouble", "difficulté");
	   map.put("truly", "vraiment");
	   map.put("trumpet", "trompette");
	   map.put("trust", "confiance");
	   map.put("truth", "vérité");
	   map.put("turns", "se tourne");
	   map.put("twice", "deux fois");
	   map.put("tyrant", "tyran");
	   map.put("ulysses", "Ulysse");
	   map.put("uncle", "oncle");
	   map.put("under", "sous");
	   map.put("understand", "comprendre");
	   map.put("undertake", "entreprendre");
	   map.put("undone", "défait");
	   map.put("unhappy", "malheureux");
	   map.put("unknown", "inconnue");
	   map.put("unless", "sauf si");
	   map.put("until", "jusqu'à");
	   map.put("unworthy", "indigne");
	   map.put("utter", "prononcer");
	   map.put("valentine", "valentine");
	   map.put("valiant", "vaillant");
	   map.put("valour", "valeur");
	   map.put("vantage", "avantage");
	   map.put("vengeance", "vengeance");
	   map.put("venice", "venise");
	   map.put("version", "version");
	   map.put("victory", "la victoire");
	   map.put("villain", "scélérat");
	   map.put("viola", "alto");
	   map.put("violent", "violent");
	   map.put("virtue", "vertu");
	   map.put("visit", "visite");
	   map.put("voice", "voix");
	   map.put("walls", "des murs");
	   map.put("warlike", "guerrier");
	   map.put("warrant", "mandat");
	   map.put("waste", "déchets");
	   map.put("watch", "regarder");
	   map.put("water", "eau");
	   map.put("wealth", "richesse");
	   map.put("weapons", "armes");
	   map.put("weary", "se lasser");
	   map.put("weeds", "mauvaises herbes");
	   map.put("unknown", "inconnue");
	   map.put("weeping", "larmes");
	   map.put("weight", "poids");
	   map.put("welcome", "Bienvenue");
	   map.put("wench", "jeune fille");
	   map.put("whence", "d'où");
	   map.put("where", "où");
	   map.put("whether", "qu'il s'agisse");
	   map.put("which", "lequel");
	   map.put("while", "tandis que");
	   map.put("whither", "où");
	   map.put("whole", "entier");
	   map.put("whore", "putain");
	   map.put("whose", "dont");
	   map.put("widow", "veuve");
	   map.put("willing", "prêt");
	   map.put("window", "la fenêtre");
	   map.put("wings", "ailes");
	   map.put("winter", "winter");
	   map.put("wisdom", "sagesse");
	   map.put("witch", "sorcière");
	   map.put("withal", "avec");
	   map.put("within", "dans");
	   map.put("without", "sans pour autant");
	   map.put("witness", "témoin");
	   map.put("wives", "épouses");
	   map.put("wolsey", "Wolsey");
	   map.put("woman", "femme");
	   map.put("wonder", "merveille");
	   map.put("works", "travaux");
	   map.put("world", "monde");
	   map.put("worse", "pire");
	   map.put("worship", "culte");
	   map.put("worth", "vaut");
	   map.put("would", "aurait");
	   map.put("wound", "blessure");
	   map.put("wounded", "blessés");
	   map.put("wrath", "colère");
	   map.put("wretch", "misérable");
	   map.put("write", "écrire");
	   map.put("written", "écrit");
	   map.put("wrong", "faux");
	   map.put("wrought", "forgé");
	   map.put("yield", "rendement");
	   map.put("yonder", "là-bas");
	   map.put("young", "Jeune");
	   map.put("yours", "le tiens");
	   map.put("yourself", "toi même");
	   map.put("youth", "jeunesse");
	   
	   
	   
	   return map;
   }
   private static  String replaceTag(String str,Map<String,String> map) {
	 
	   for(Map.Entry<String, String> entry : map.entrySet()) {
		   if(str.contains(entry.getKey())) {
			   str= str.replace(entry.getKey(), entry.getValue());
		   }
		  
	   }
	   return str;
	 
   }
   
   }

